### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by tomcatt360**
Fixed "chang" to "change" in first comment.

### CODE REVIEW

**Comment by EmergentBehavior** [comment]
Hi @tomcatt360. We request that all contributors of PRs [fill out our CLA](http://storj.io/cla). Thanks!

**Comment by tomcatt360** [comment]
I'm pretty sure that I have already, but I can do it again if you want. :)

**Comment by EmergentBehavior** [comment]
My bad, you're right. Can merge!

**Comment by tomcatt360** [comment]
Thank You!

**Pull request merged**
